services:
  web:
    image: mcr.microsoft.com/dotnet/aspnet:8.0
    container_name: todo_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DBString=Server=db;Database=TodoDb;User Id=sa;Password=Str0ngP@ssw0rd!;TrustServerCertificate=True;

  db:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: db
    ports:
      - "1433:1433"
    environment:
      - MSSQL_PID=Developer
      - SA_PASSWORD=Str0ngP@ssw0rd!
      - ACCEPT_EULA=Y
